-- MYSQL data types
-- String types
-- Numeric types
-- Date and Time types
-- Blob types                   -- for storing binary
-- spatial types                -- for storing geometric or geographical values