-- Solve today's problems not future problems.
-- Simplicity is the ultimate sophistication.
-- Don't be afraid of changes in the future. 
-- Model a database with the information you currently have.
