-- Type of environments
    -- production environment, where our users access our databases.
    -- staging environment
    -- testing environment
    -- development environment
-- Assuming each environment has multiple databases.
-- All the databases in various environments should be consistent.